src/Entity/Users.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * @ORM\Entity(repositoryClass="App\Repository\UsersRepository")
 * @ORM\Entity
 * @UniqueEntity("Username")
 * @UniqueEntity("Mail")
 */ 
class Users implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Mail;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setUsername(string $Username): self
    {
        $this->Username = $Username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    public function eraseCredentials()
    {

    }

    public function getSalt()
    {

    }

    public function getMail(): ?string
    {
        return $this->Mail;
    }

    public function setMail(string $Mail): self
    {
        $this->Mail = $Mail;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] =  'ROLE_USER';
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;



use App\Entity\Users;
use App\Entity\Comments;
use App\Form\RegistrationType;
use App\Form\ConnexionType;

class SecurityController extends AbstractController
{
    /**
     * @Route("/inscription", name="security_registration")
     */
    public function Registration(Request $request, EntityManagerInterface $manager, UserPasswordEncoderInterface $encoder)
    {
        $user = new Users(); //On creer un utilisateur vide.

        $form = $this->createForm(RegistrationType::class, $user); //On creer le formulaire, l'utilisateur nouvellement crée recevra les valeurs du formulaire.

        $form->handleRequest($request); //Analyse de la requete

        if($form->isSubmitted() && $form->isValid()) // Si la requête à lieu, est que les infos sont valide
        {
            $hash = $encoder->encodePassword($user, $user->getPassword());

            $user->setPassword($hash);

            $manager->persist($user);
            $manager->flush();

            return $this->redirectToRoute('security_connexion'); //On redirige vers la page de connexion.
        }

        return $this->render("security/registration.html.twig", [
            'form' => $form->createView() // On passe en argument le paramètre form.
        ]);

    }

    /**
     * @Route("/connexion", name="security_connexion")
     */
    public function Connexion(Request $request)
    {
        $user = new Users(); //On creer un utilisateur vide.

        $form = $this->createForm(ConnexionType::class, $user); //On creer le formulaire, l'utilisateur nouvellement crée recevra les valeurs du formulaire.


        return $this->render("security/connexion.html.twig", [
            'form' => $form->createView()
        ]);


    }

    /**
     * @Route("/deconnexion", name="security_logout")
     */
    public function Logout()
    {

    }

    /**
     * @Route("/moderation", name="moderation")
     */
    public function moderation()
    {
        $user = new Users();

        $repo = $this->getDoctrine()->getRepository(Users::class);

        $comment = new Comments();

        $repoComments = $this->getDoctrine()->getRepository(Comments::class);

        $comment = $repoComments->findBy([
            "Report" => 1
        ]);

        $user = $repo->findAll();
        return $this->render("security/moderation.html.twig", [
            "user" => $user,
            "comment" => $comment
        ]);
    }

    /**
     * @Route("/moderation/{id}", name="moderation_role_administrator")
     */
    public function moderationChangeRoleToAdministrator($id, EntityManagerInterface $manager)
    {
        $user = new Users();

        $repo = $this->getDoctrine()->getRepository(Users::class);

        $user = $repo->find($id);

        $user->setRoles(array("ROLE_ADMINISTRATOR"));
        $manager->flush();
        $manager->clear();

        return $this->redirectToRoute("moderation");
    }

    /**
     * @Route("/moderation/admin/{id}", name="moderation_role_moderator")
     */
    public function moderationChangeRoleToModerator($id, EntityManagerInterface $manager)
    {
        $user = new Users();

        $repo = $this->getDoctrine()->getRepository(Users::class);

        $user = $repo->find($id);

        $user->setRoles(array("ROLE_MODERATOR"));
        $manager->flush();
        $manager->clear();

        return $this->redirectToRoute("moderation");
    }


}

templates/security/connexion.html.twig
{% extends "base.html.twig" %}


{% block menu %}
    <li class="nav-item">
        <a id="Forum" class="nav-link" href="{{ path("security_registration") }}">Inscription</a>
    </li>
    <li class="nav-item">
        <a id="Forum" class="nav-link" href="{{ path("security_connexion") }}">Connexion</a>
    </li>
{% endblock %}

{% block body %}
    
    <div class="jumbotron forum-form">
         <img src="https://t3.ftcdn.net/jpg/00/29/84/92/240_F_29849268_U1XPi0zHFgVPS3vo8PtTPKNOo1eY7jmS.jpg" alt="Une image" id="Register_Background">

        {{ form_start(form, {'attr': {'id' : 'Connexion'}, 'method': 'post', 'action': path('security_connexion') }) }}
        {{ form_row(form.Username, {'attr' : {'placeholder' : 'Nom d\'utilisateur'}, 'full_name' : '_username'})}}
        {{ form_row(form.Password, {'attr' : {'placeholder' : 'Mot de passe'}, 'full_name' : '_password'})}}

        <div class="button-form">
            <button type="submit" class="btn btn-success"> Se connecter </button>
        </div>
        {{ form_end(form)}}
    </div>

   
{% endblock %}

templates/security/moderation.html.twig
{% extends "base.html.twig" %}

{% block body %}
{% if is_granted("ROLE_MODERATOR") or is_granted("ROLE_ADMINISTRATOR") %}
{% if is_granted("ROLE_ADMINISTRATOR") %}
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Nom d'utilisateur</th>
            <th scope="col">Email</th>
            <th scope="col">Rôle</th>
            <th scope="col">administration</th>
        </tr>
    </thead>
    <tbody>
        {% for users in user %}
            <tr class="table-light forum-table">
                <td> {{ users.username }} </td>
                <td> {{ users.mail }}</td>
                <td> {{ users.roles|join(', ', ' and ') }}</td>
                <td> <a href=" {{ path("moderation_role_administrator", {"id": users.id}) }} "> administateur</a> | <a href=" {{ path("moderation_role_moderator", {"id": users.id}) }} "> moderateur</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
<div id="Moderation-Title" > <h1>Commentaires signalés</h1> </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col"> Auteur </th>
                <th scope="col"> Contenu du message </th>
                <th scope="col"> Date de création </th>
                <th scope="col"> Action</th>
            </tr>
        </thead>
        <tbody>
        {% for comments in comment %}
            <tr class="table-light forum-table"> 
                <td> {{ comments.User.Username }} </td>
                <td> {{ comments.Content|raw }} </td>
                <td> {{ comments.createdAt| date("h/m/y") }} </td>
                <td> <a href="{{ path("removeReportedComment", {"commentId": comments.id}) }}">Supprimer</a> | <a href="{{ path("authorizedReportedComment", {"commentId": comments.id}) }}">Autoriser</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        <h1>Accés Interdit</h1>

{% endif %}

{% endblock %}

templates/security/registration.html.twig
{% extends "base.html.twig" %}




{% block menu %}
    <li class="nav-item">
        <a id="Forum" class="nav-link" href="{{ path("security_registration") }}">Inscription</a>
    </li>
    <li class="nav-item">
        <a id="Forum" class="nav-link" href="{{ path("security_connexion") }}">Connexion</a>
    </li>
{% endblock %}

{% block body %}
    
    <div class="jumbotron forum-form">
        <img src="https://abcnatation.fr/files/club-100262137/up/ob_f23c73_inscriptions.png" alt="Une image" id="Register_Background">
        {{ form_start(form, {'attr': {'id': 'Registration'}}) }}
        {{ form_row(form.Mail)}}
        {{ form_row(form.Username)}}
        {{ form_row(form.Password)}}
        <div class="button-form">
            <button type="submit" class="btn btn-success"> S'inscrire </button>
        </div>
        {{ form_end(form)}}
    </div>
    
{% endblock %}