src/Entity/Comments.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentsRepository")
 */
class Comments
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $Content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Subjects")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Subject;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Report;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSubject(): ?Subjects
    {
        return $this->Subject;
    }

    public function setSubject(?Subjects $Subject): self
    {
        $this->Subject = $Subject;

        return $this;
    }

    public function getReport(): ?bool
    {
        return $this->Report;
    }

    public function setReport(bool $Report): self
    {
        $this->Report = $Report;

        return $this;
    }
}

src/Entity/News.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 */
class News
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $Source;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getSource(): ?string
    {
        return $this->Source;
    }

    public function setSource(?string $Source): self
    {
        $this->Source = $Source;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * @ORM\Entity(repositoryClass="App\Repository\UsersRepository")
 * @ORM\Entity
 * @UniqueEntity("Username")
 * @UniqueEntity("Mail")
 */ 
class Users implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Mail;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setUsername(string $Username): self
    {
        $this->Username = $Username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    public function eraseCredentials()
    {

    }

    public function getSalt()
    {

    }

    public function getMail(): ?string
    {
        return $this->Mail;
    }

    public function setMail(string $Mail): self
    {
        $this->Mail = $Mail;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] =  'ROLE_USER';
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Users;
use App\Entity\Subjects;
use App\Entity\Comments;
use App\Entity\News;
use App\Form\SubjectType;
use App\Form\CommentType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;

class NewsController extends AbstractController
{
    /**
     * @Route("/", name="news")
     */
    public function index()
    {
        return $this->render('news/index.html.twig');
    }

    /**
     * @Route("/archive", name="archive")
     */
    public function archive(EntityManagerInterface $manager, PaginatorInterface $paginator, Request $request)
    {
        $news = new News();
        $apiNews = file_get_contents("https://newsapi.org/v2/top-headlines?country=fr&pageSize=40&apiKey=a727be71caab4420b0862dad9c71c661");
        $data = json_decode($apiNews);

        $server = $this->getDoctrine()->getRepository(News::class);

       

        //Nouveautées globales
        foreach ($data->articles as $article)
        {
            if($server->findBy(["address" => $article->url]))
            {
                $news->setAddress($article->url);
                $news->setSource($article->source->name);
                $news->setCreatedAt(new \Datetime());
                $manager->flush();
                $manager->clear();
            }
            else
            {
                $news->setAddress($article->url);
                $news->setSource($article->source->name);
                $news->setCreatedAt(new \Datetime());
                $manager->persist($news);
                $manager->flush();
                $manager->clear();
            }
        }

        $actualTime = new \DateTime();

        $articles = $server->findAll();
        $pagination = $paginator->paginate($articles, $request->query->getInt('page', 1), 15);
        return $this->render("news/archive.html.twig", [
            "news" => $pagination,
            "actualTime" => $actualTime
        ]);
    }

    /**
     * @Route("/archive/removeOldArchive", name="removeOldArchives")
     */
    public function removeOldArchives(EntityManagerInterface $manager)
    {
        $news = new News();
        $repository = $this->getDoctrine()->getRepository(News::class);

        $news = $repository->findAll();

        foreach($news as $index)
        {
            $interval = \date_diff(new \DateTime(), $index->getCreatedAt());
            if($interval->format("%m")  >= 1)
            {
                $manager->remove($index);
                $manager->flush();
            }
        }
        return $this->redirectToRoute("archive");
    }

     /**
     * @Route("/mentions", name="mentions")
     */
    public function showMentions()
    {
        return $this->render("news/mentions.html.twig");
    }

    /**
     * @Route("/forum", name="forum")
     */
    public function forum(Request $request, EntityManagerInterface $manager, PaginatorInterface $paginator)
    {
        $subject = new Subjects(); //On creer entitée.

        $form = $this->createForm(SubjectType::class, $subject); //On creer le form, $subject recevra les valeurs.
        $form->handleRequest($request); //Analyse de la requete

        if($form->isSubmitted() && $form->isValid()) // Si la requête à lieu, est que les infos sont valide
        {
            $subject->setTitle($subject->getTitle());
            $subject->setContent($subject->getContent()); 
            $subject->setCreatedAt(new \DateTime());
            $subject->setUser($this->getUser());

            $manager->persist($subject);
            $manager->flush();
            return $this->redirectToRoute('forum'); //On redirige vers la page du forum.
        }

        $repo = $this->getDoctrine()->getRepository(Subjects::class); //Variable qui va chercher dans la base de données contenant la classe Comments
        $subjects = $repo->findAll();
        $pagination = $paginator->paginate($subjects, $request->query->getInt('page', 1), 15);
        return $this->render('news/forum.html.twig', [
            "subjects" => $pagination,
            'form' => $form->createView() // On passe en argument le paramètre form.
        ]);
    }

    /**
     * @Route("/forum/{id}", name="subject")
     */
    public function showForumSubjects($id, Request $request, EntityManagerInterface $manager, PaginatorInterface $paginator)
    {
        $repo = $this->getDoctrine()->getRepository(Subjects::class);
        $subjects = $repo->find($id);

        $comments = new Comments();
        $form = $this->createForm(CommentType::class, $comments);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $comments->setContent($comments->getContent());
            $comments->setCreatedAt(new \DateTime());
            $comments->setUser($this->getUser());
            $comments->setSubject($subject = $repo->find($id));
            $comments->setReport(0);

            $manager->persist($comments);
            $manager->flush();
            return $this->redirectToRoute('subject', ['id' => $id]);
        }

        $commentsRepo = $this->getDoctrine()->getRepository(Comments::class);
        $comment = $commentsRepo->findby(['Subject' => $id]);
        $pagination = $paginator->paginate($comment, $request->query->getInt('page', 1), 8);

        return $this->render('news/subjects.html.twig', [
            "subject" => $subjects,
            "comments" => $pagination,
            "form" => $form->createView()
        ]);
    } 

    /**
     * @Route("forum/delete/{subjectId}", name="removeSubject")
     */
    public function removeSubject(EntityManagerInterface $manager, $subjectId)
    {
        $repository = $this->getDoctrine()->getRepository(Subjects::class);
        $subject = $repository->find($subjectId);
        $manager->remove($subject);
        $manager->flush();
        return $this->redirectToRoute("forum");
    }

    /**
     * @Route("/forum/{subjectId}/{commentId}", name="removeComment")
     */
    public function removeComment(EntityManagerInterface $manager, $subjectId, $commentId)
    {
        $repository = $this->getDoctrine()->getRepository(Comments::class);
        $comment = $repository->find($commentId);
        $manager->remove($comment);
        $manager->flush();
        return $this->redirectToRoute("subject", ["id" => $subjectId]);
    }

    /**
     * @Route("/forum/comment/reported/{subjectId}/{commentId}", name="reportedComment")
     */
    public function reportedComment($subjectId, $commentId, EntityManagerInterface $manager)
    {
        $comment = new Comments();
        
        $repository = $this->getDoctrine()->getRepository(Comments::class);

        $comment = $repository->find($commentId);
        $comment->setReport(1);
        $manager->persist($comment);
        $manager->flush();

        return $this->redirectToRoute("subject", ["id" => $subjectId]);
    }

    /**
     * @Route("/forum/comment/remove/{commentId}", name="removeReportedComment")
     */
    public function removeReportedComment(EntityManagerInterface $manager, $commentId)
    {
        $repository = $this->getDoctrine()->getRepository(Comments::class);
        $comment = $repository->find($commentId);
        $manager->remove($comment);
        $manager->flush();
        return $this->redirectToRoute("moderation");
    }

    /**
     * @Route("/forum/comment/authorized/{commentId}", name="authorizedReportedComment")
     */
    public function authorizedReportedComment(EntityManagerInterface $manager,$commentId)
    {
        $comment = new Comments();
        
        $repository = $this->getDoctrine()->getRepository(Comments::class);

        $comment = $repository->find($commentId);
        $comment->setReport(0);
        $manager->persist($comment);
        $manager->flush();
        return $this->redirectToRoute("moderation");
    }
}

templates/news/archive.html.twig
{% extends "base.html.twig" %}

{% block body %}

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Source</th>
            <th scope="col">Liens</th>
            <th scope="col">Date de publication</th>
            {% if is_granted("ROLE_ADMINISTRATOR") == true %}
                <th scope="col">Ancienneté</th>
            {% endif %}
        </tr>
    </thead>
    <tbody class="archive_list">
        {% for article in news %}
            <tr class="table table-light archive-table">
                <td> {{ article.source }} </td>
                <td> <a href=" {{ article.address }}"> {{ article.address|length > 60 ? article.address|slice(0, 60)~ '...' : article.address}} </td> 
                <td> {{ article.createdAt| date("d/m/Y") }} </td>
                {% set diff = date(actualTime).diff(date(article.createdAt)) %}
                {% if is_granted("ROLE_ADMINISTRATOR") == true %}
                    <td> {{ diff | date("%m mois") }}</td>
                {% endif %}
            </tr>
         {% endfor %}
    </tbody>
</table>
 <div id="Pagination"> {{ knp_pagination_render(news) }} </div>


{% if is_granted("ROLE_ADMINISTRATOR") == true %}
<div class="jumbotron" id="Archives_Delete">
    <h1>Administation</h1>
    <h5>Supprimer archives vieilles d'un mois ?</h5>
     <a class="btn btn-success" href="{{ path("removeOldArchives") }}"> Supprimer </a>
</div>
{% endif %}

{% endblock %}

templates/news/forum.html.twig
{% extends "base.html.twig" %}

{% block menu %}
    {% if not app.user %}
        <li class="nav-item">
            <a id="Forum" class="nav-link" href="{{ path("security_registration") }}">Inscription</a>
        </li>
        <li class="nav-item">
            <a id="Forum" class="nav-link" href="{{ path("security_connexion") }}">Connexion</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a id="Forum" class="nav-link" href="{{ path("security_logout") }}">Se déconnecter</a>
        </li>
    {% endif %}
{% endblock %}

{% block body %}

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Titre</th>
                <th scope="col">Messages</th>
                <th scope="col">Nom d'utilisateur</th>
                <th scope="col">Date de création</th>
                {% if is_granted("ROLE_ADMINISTRATOR") == true %}
                    <th scope="col">Actions</th>
                {% elseif is_granted("ROLE_MODERATOR") == true  %}
                    <th scope="col">Actions</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for subject in subjects %}
                <tr class="table-light forum-table">
                    <td><a href="{{ path("subject", {'id': subject.Id}) }}">{{subject.Title}}</a></td>
                    <td> 
                       {{  subject.Content|length > 50 ?  subject.Content|striptags|slice(0,50) ~ '...' : subject.Content|striptags|raw }}   
                    </td> 
                    <td>{{ subject.getUser.username }}</td>
                    <td>{{ subject.createdAt | date('d/m/Y') }}</td>
                    {% if is_granted("ROLE_ADMINISTRATOR") == true %}
                        <td><a href=" {{ path("removeSubject", {"subjectId": subject.ID }) }} ">supprimer</a></td>
                    {% elseif is_granted("ROLE_MODERATOR") == true  %}
                        <td><a href=" {{ path("removeSubject", {"subjectId": subject.ID }) }} ">supprimer</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {{ knp_pagination_render(subjects) }} 
    <div class="jumbotron forum-form">
        {% if not app.user %}
        <div id="Not_Connected">
            <p>Veuillez vous <a href="{{ path("security_connexion") }}"> connecter  </a>  pour creer un sujet</p>
        </div>
            
        {% else %}
            {{ form_start(form) }}
            {{ form_row(form.Title) }}
            {{ form_row(form.Content, {"attr": {"placeholder": "Test"}}) }}
            <div class="button-form">
                 <button type="submit" class="btn btn-success"> Creer </button>
            </div>
            {{ form_end(form) }}
        {% endif %}
    </div>
    
{% endblock %}

templates/news/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="jumbotron news-list"> 
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link"  id="Sports"  href="/">Sports</a>
        </li>
        <li class="nav-item">
            <a class="nav-link"  id="Health" href="/">Santé</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="Sciences"  href="/">Sciences</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="Technologies"  href="/">Technology</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="Entertainments" href="/">Divertissements</a>
        </li>
    </ul>
</div> 

{% endblock %}

templates/news/subjects.html.twig
{% extends "base.html.twig"%}

{% block menu %}
    {% if not app.user %}
        <li class="nav-item">
            <a id="Forum" class="nav-link" href="{{ path("security_registration") }}">Inscription</a>
        </li>
        <li class="nav-item">
            <a id="Forum" class="nav-link" href="{{ path("security_connexion") }}">Connexion</a>
        </li>
    {% else %}
         <li class="nav-item">
            <a id="Forum" class="nav-link" href="{{ path("security_logout") }}">Se déconnecter</a>
        </li>
    {% endif %}
{% endblock %}

{% block body %}

<div class="list-group">
    <div class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ subject.getUser.username }}</h5>
            <small>{{ subject.createdAt | date("h/m/Y") }}</small>
        </div>
        <p class="mb-1"> {% autoescape %} {{ subject.Content|raw }} {% endautoescape %}  </p>
    </div>
    {% for comment in comments %} 
    <div class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ comment.getUser.username }}</h5> <br>
            <small>
                {% if is_granted("ROLE_ADMINISTRATOR") == true %}
                    {{ comment.createdAt | date("h/m/Y") }} <br>
                    <a href="{{ path("removeComment", {"subjectId": subject.Id, "commentId": comment.Id }) }}">Supprimer</a> <br>
                    <a href="{{ path("reportedComment", {"commentId": comment.Id, "subjectId": subject.Id}) }} ">Signaler</a>
                {% elseif is_granted("ROLE_MODERATOR") == true %}
                    {{ comment.createdAt | date("h/m/Y") }} <br>
                    <a href="{{ path("removeComment", {"subjectId": subject.Id, "commentId": comment.Id }) }}">Supprimer</a> <br>
                    <a href="{{ path("reportedComment", {"commentId": comment.Id, "subjectId": subject.Id }) }} ">Signaler</a>
                {% else %}
                    {{ comment.createdAt | date("h/m/Y") }} <br>
                    <a href="{{ path("reportedComment", {"commentId": comment.Id, "subjectId": subject.Id }) }} ">Signaler</a>
                {% endif %}
            </small>
        </div>
        <p class="mb-1">  {{ comment.Content|raw }}              
            {% if comment.report == 1 %}
                Ce commentaire a été signalé, un modérateur s'en occupera prochainement. 
            {% endif %}
        </p>
    </div>
    {% endfor %} 
    {{ knp_pagination_render(comments) }} 
</div>

<div class="jumbotron forum-form">
    {% if not app.user %}
        <div id="Not_Connected">
            <p>Veuillez vous <a href="{{ path("security_connexion") }}"> connecter  </a>  pour commenter</p>
        </div>
    {% else %}
       {{ form_start(form) }}
            {{ form_row(form.Content) }}
            <div class="button-form">
                 <button type="submit" class="btn btn-success"> Creer </button>
            </div>
            {{ form_end(form) }}
    {% endif %}
</div>

{% endblock %}